### ISSUE TITLE
Saving associated models.

### ISSUE THREAD

**Issue by efluxy** [j4mie/paris#108]
Suppose we have two entities __Classroom__ and __Student__, with the following relationship:
```
    Classroom --< Student
```

The following code will successfully yield an array of __Student__ instances associated with a __Classroom__ instance.
```php
$students = $classroom->students()->get_many();
```
However the following will not work:
```php
$classroom->students = array($student_1, $student_2);
$classroom->save();
```

Instead, the following needs to be done:
```php
$student_1->classroom_id = $classroom->id;
$student_2->classroom_id = $classroom->id;
$student_1->save();
$student_2->save();
```

This defeats the purpose of an ORM, doesn't it? Or does Paris ORM has a way to handle that which I may have missed?

**Comment by treffynnon** [comment]
It's not in the design of Paris or a requirement of an ORM.
