### ISSUE TITLE
Execute delete method of models

### ISSUE THREAD

**Issue by rjgamer** [j4mie/paris#110]
Hi,

is it possible to integrate an execution of the delete method when deleting records / model entities over ORM (Paris).

Current solution:
$foos = Model::factory('Foo')->where_raw('`doo` IS NULL')->find_many();
foreach ($foos as $foo) {
    $foo->delete();
}

Better solution (one lining code):
Model::factory('Foo')->where_raw('`doo` IS NULL')->delete_many();

Its more a feature request than a issue and needs an change on the ORMWrapper.

**Comment by treffynnon** [comment]
https://github.com/j4mie/paris#feature-complete

**Comment by rjgamer** [comment]
Sorry, my fault...
