### ISSUE TITLE
Global table prefix

### ISSUE THREAD

**Issue by zenn1989** [j4mie/paris#112]
Some times developer's use one database to 2 or more similar project's and to prevent overwrite tables - used prefix. But in the paris is no way to configure table prefix (used only to table name and nothing etc).
The simple way - add same config and change table name in Model::_get_table_name(). 
Also, why method _get_table_name() marked as "protected"? Other developer's can't extend it.

**Comment by treffynnon** [comment]
> Some times developer's use one database to 2 or more similar project's
and to prevent overwrite tables - used prefix. But in the paris is no way
to configure table prefix (used only to table name and nothing etc).

This has been discussed a few times already. Please review past tickets.

> Also, why method _get_table_name() marked as "protected"? Other
developer's can't extend it.

The reasons for this decision are locked away in the mind of @j4mie 4 or 6
years ago. Now no-one knows the original reason!
