### ISSUE TITLE
belongs_to has a problem with namespace

### ISSUE THREAD

**Issue by lokeb** [j4mie/paris#113]
I recently moved all my code to a namespace and everything was working okay until I faced the relation belongs_to, and I think it will have problems with other relations as well. My relation is defined as follows in a namespaced model as follows :
```php
namespace blue;
class Child extends \Model {
   public function parent() {
       return $this->belongs_to('Parent');
   }
   public function some_method() {
     $result = $this->parent()->find_one(); 
   }
}
```

On calling some_method, the belongs_to call requests the registered autoloader for the Parent class, but the autoloader returns blue\Parent class, which does not serve the purpose for Paris. Paris should rather ask for blue\Parent. On defining the relation as belongs_to('blue\Parent'), it does not understand that the class is namespaced and expects blue\Parent table to be present. This is a serious problem, and has brought down my entire application. Will you please help?

**Comment by lokeb** [comment]
I think there was some problem in me specifying the relation with namespace. It is working after I corrected it. Now, the relations needs to be defined as __NAMESPACE__.'\Parent', which is okay, but given that the child is contained in blue, shouldn't parent be expected to be contained in blue as well?

**Comment by treffynnon** [comment]
You need to use the correct namespace and generally recommend to include the full namespace in this instance as you have done.
