### ISSUE TITLE
hasMany has limitations?!

### ISSUE THREAD

**Issue by lokeb** [j4mie/paris#114]
Is it possible to make queries that work on hasMany? What I mean is if a->hasMany(b), then can I call 
```a->find_many()->b()->find_many()``` ?

The current implementation returns an array, which requires each ```a``` to request for many ```b```s. While the returned data is as one would want, the sorting order of the records is problematic, because one would expect all the ```b```s to be ordered as per its table, which will only be possible if the implementation supported the above request, i.e., ```find_many()``` returned an object that could be queried further in continuity. 

Does the current implementation support such queries in any way?

**Comment by treffynnon** [comment]
Chaining like this is not supported.

**Comment by lokeb** [comment]
You are late, but I have a solution!
