### ISSUE TITLE
MyModel extends Model outputs Fatal error: Class 'MyModel' not found in vendor/j4mie/paris/paris.php on line 121

### ISSUE THREAD

**Issue by nmpribeiro** [j4mie/paris#116]
Hi there, I'm not undestanding how to make MyModel available to the ORM...

 Fatal error: Class 'MyModel ' not found in vendor/j4mie/paris/paris.php on line 121

<?php namespace MyApp\Model;

class MyModel extends \Model
{
  
}

In HomeController, I've asked to use MyModel instead of ORM's Model:
use MyApp\Model\MyModel;

and in the indexAction:
$mymodel = MyModel::factory('MyModel')->order_by_desc('timestamp')->find_many();

I can get it to work if I don't use namespaces, so the namespace 'MyApp\Models\' need to be thrown at the ORM (wraper?). But I'm not sure about it. Any help would be great

Thanks in advance

**Comment by nmpribeiro** [comment]
I see...
$mymodels = \Model::factory(MyModel::class)->order_by_desc('timestamp')->find_many();

now fixing the table name :)

**Comment by nmpribeiro** [comment]
<?php namespace MyApp\Model;

class MyModel extends \Model
{
  public static $_table = 'myapp_mymodels';
}

This might be handy for anyone else

**Comment by treffynnon** [comment]
Use the full namespace in the call to `factory`.

```php
$m = Model::factory('MyApp\\Model');
```
