### ISSUE TITLE
Namespaces and Class naming collision problem: "Model"

### ISSUE THREAD

**Issue by ZaDarkSide** [j4mie/paris#121]
In Paris there is defined a class named generic as "Model", this might conflict with a user created class because of the name.

```php
    class Model {
        // Default ID column for all models. Can be overridden by adding
        // a public static _id_column property to your model classes.
        const DEFAULT_ID_COLUMN = 'id';
        ....
```

The only solution here is either to change the generic name "Model" to something like "ParisModel" or the proper solution to implement a Namespace so that collisions with application code classes can't occur.

I've hit this problem myself when I was trying to define a class "Model" in my application and I will submit this as a bug not as an enhancement because Namespaces are available on PHP since v5.3.x and to update the required PHP version from v5.2.x to v5.3.x would likely cause no trouble.

Idiorm doesn't "suffers" from this problem because the class names are more sanely named:

```
class ORM
class IdiormString
class IdiormResultSet
class IdiormStringException
class IdiormMethodMissingException
```

Still Idiorm should use Namespaces also.

I'm using these libraries via Composer in other scenarios there is no problem you just edit the "offending" class name in the library. But building a tool-chain around Composer and other tools you are forced to use the library "as is".

**Comment by treffynnon** [comment]
That's a BC break and would require a major version number bump so no.

**Comment by ZaDarkSide** [comment]
Well in Paris the Namespaces are already somewhat (ab)used:

```php
        /**
         * Set a prefix for model names. This can be a namespace or any other
         * abitrary prefix such as the PEAR naming convention.
         *
         * @example Model::$auto_prefix_models = 'MyProject_MyModels_'; //PEAR
         * @example Model::$auto_prefix_models = '\MyProject\MyModels\'; //Namespaces
         *
         * @var string $auto_prefix_models
         */
        public static $auto_prefix_models = null;
```
What's the BC break you are talking about? I'm not suggesting changing the class name. I only said there are 2 solutions I could think of regarding this library. There is another solution to use Namespaces inside the application. But still I think is a valid point I'm making here.

Adding Namespaces will not brake anything, the only think it should affect is the lowest PHP version required to use the library as I already said.

**Comment by treffynnon** [comment]
Which is a bc break...

**Comment by ZaDarkSide** [comment]
If adding Namespaces is a BC break, then why not support PHP v5.0.x also? Or even better let's support the oldest version of PHP that exists currently in use so that Paris will be backwards compatible with any version of PHP.

**Comment by treffynnon** [comment]
It supports 5.2 and there is a prominent notice in the readme for at least
a year now that no bc breaks will be tolerated. Removing support for 5.2 is
a break and adding namespaces is a new feature.

Rename your applications model class to something descriptive or use a
different library. Or getting radical here you could maintain your own
fork....

It really is that simple.

**Comment by ZaDarkSide** [comment]
Okay, I will do the fork then.
Thank you for your answers.
