### ISSUE TITLE
read from slave, then delete from master

### ISSUE THREAD

**Issue by shucream0117** [j4mie/paris#124]
Hi.

First, record is read from slave.
(like this↓)
```
$user = Model::factory('User', 'slave')->find_one(1);
```

Second, I'd like to delete this record
```
$user->delete();
```

but, `$user` has connection to "slave".
Is there any way to "read from slave, delete from master" ?

**Comment by treffynnon** [comment]
Use two queries. One for your primary DB and a second for your secondary DB.

**Comment by shucream0117** [comment]
@treffynnon 

thank you for replying.
sorry, there was a mistake in my question. I modified sentence.

Is the way to `"read from slave, delete from master"` like following?
```
$id = 1;
if (Model::factory('User', 'slave')->find_one($id)) { // read from slave
    $user = Model::factory('User', 'master')->find_one($id); // find from master
    $user->delete(); // delete from master
}
```

**Comment by treffynnon** [comment]
I think that looks about right.

**Comment by shucream0117** [comment]
ok, thanks
