### ISSUE TITLE
Saving associations?

### ISSUE THREAD

**Issue by quasipickle** [j4mie/paris#126]
Does Paris save associated models?

For example, if I have a User model and each User has an associated Profile model, does the Profile get saved when I save the User?

**Comment by treffynnon** [comment]
No there are no cascading saves in Paris: http://paris.readthedocs.io/en/latest/philosophy.html

If you need this then Eloquent ORM might be better fit : https://laravel.com/docs/5.4/eloquent-relationships - you'll notice it is very similar to Paris/Idiorm - this is not accident Taylor used them as inspiration for his Eloquent ORM when he was writing it.
