### ISSUE TITLE
Re-write for PSR, PHP 7.1+?

### ISSUE THREAD

**Issue by tag** [j4mie/paris#129]
@treffynnon , how would you feel about opening a branch for a 2.0 version with the following goals?

* PHP 7.1+ only
* PSR-1, PSR-2 (code style, naming)
* PSR-4 (name spacing, auto-loading)
* (possibly; I haven't looked into it) PSR-16 (simple caching)
* Updating documentation & PHPDoc blocks
* EDIT: PSR-3 (logging)
* Consistent with the goals of Paris/Idiorm, not adding new features, EXCEPT IDE helpers (e.g., #128)

[Link to PSR standards.](http://www.php-fig.org/psr/)

I feel like Paris is beginning to show its age, and it's time to have a version that drops support for 5.2 (and some of the workarounds necessary to support it) and embraces namespacing. I'm okay with this being a backward-compatible break (which would be necessary for PSRs 2 & 4)

I'll have some time in May to work on this, but wanted to get your support before spending time on it.

**Comment by treffynnon** [comment]
This has been brought up a few times and my feeling is that it's outside the scope of Paris. Additionally, with Eloquent ORM already fulfilling most of those criteria and looking a lot like Paris and Idiorm in terms of API I am not sure the effort is worthwhile. What would it be providing that Eloquent doesn't already? How would it be more useful to implementers?

**Comment by tag** [comment]
I realize it's been brought up several times—which is partly why I did so again. This suggests to me there is some interest in carrying Paris forward to PHP 7.1. I'll have some time this summer to work on it, and getting your buy-in would partially dictate whether/how much time I spend on it.

For me, I typically only do small projects any more, for which Paris is ideal. Plus, I know it and am comfortable with it. I'd still like to see it updated, and my suspicion is others would as well.

The point of Paris isn't to compete with Eloquent. As you've said many times, it's an 80/20 solution, and I'm content with that. But when I need to dig into the code to figure something out, it would be easier to have the code in use a standard similar to other libraries.

Are you suggesting that implementers should not use Paris in the future, and transition to Eloquent instead?

**Comment by treffynnon** [comment]
But when I need to dig into the code to figure something out, it would be
easier to have the code in use a standard similar to other libraries.

This is what, I feel, Eloquent already provides. If you're starting a new
project and desire these features then I'd recommend using Eloquent as I've
done in the past.

Are you suggesting that implementers should not use Paris in the future,
and transition to Eloquent instead?

Well that is a choice for individuals to make themselves.

That said I have used Eloquent successfully for a number of projects as a
replacement for Paris. It suited the small and simple need perfectly. Given
its origins this makes sense.

I have not used Idiorm or Paris in a new project for a few years - the
project is still maintained for those users who have it out in the wild or
still desire to use it (there are still many projects using it at my
previous place of work for instance).


Jamie and I took the decision to freeze feature development a while ago now
and I still think that was the right choice. There is a pretty good upgrade
path for those that choose to (Eloquent) and maintenance for those
currently using or deciding to use Paris.

======================================

All that said, you can, of course, fork and start a new project - the
licence is open and permissible. I just don't think that Paris is the right
place for this work going forward.

Thank you for your contributions to Paris and Idiorm - I hope you can see
the reasoning behind the decision.

**Comment by treffynnon** [comment]
> But when I need to dig into the code to figure something out, it would be
easier to have the code in use a standard similar to other libraries.

This is what, I feel, Eloquent already provides. If you're starting a new
project and desire these features then I'd recommend using Eloquent as I've
done in the past.

> Are you suggesting that implementers should not use Paris in the future,
and transition to Eloquent instead?

Well that is a choice for individuals to make themselves.

That said I have used Eloquent successfully for a number of projects as a
replacement for Paris. It suited the small and simple need perfectly. Given
its origins this makes sense.

I have not used Idiorm or Paris in a new project for a few years - the
project is still maintained for those users who have it out in the wild or
still desire to use it (there are still many projects using it at my
previous place of work for instance).

---

Jamie and I took the decision to freeze feature development a while ago now
and I still think that was the right choice. There is a pretty good upgrade
path for those that choose to (Eloquent) and maintenance for those
currently using or deciding to use Paris.

---

All that said, you can, of course, fork and start a new project - the
licence is open and permissible. I just don't think that Paris is the right
place for this work going forward.

Thank you for your contributions to Paris and Idiorm - I hope you can see
the reasoning behind the decision.

**Comment by richp10** [comment]
I really like paris / idiorm but had all sorts of problems when switching to PHP7

There is already a good fork, which is working well for me:
https://github.com/voku/paris

It would be a shame if idiorm dwindled because of lack of namespacing and I wonder if there might be some way of voku being an 'official' php7 / namespaced fork?

**Comment by treffynnon** [comment]
Loads of issues with php7? Please can you elaborate further. Test suite is
passing against 7 so...

On 31 Mar 2017 7:15 p.m., "richp10" <notifications@github.com> wrote:

I really like paris / idiorm but had all sorts of problems when switching
to PHP7

There is already a good fork, which is working well for me:
https://github.com/voku/paris

It would be a shame if idiorm dwindled because of lack of namespacing and I
wonder if there might be some way of voku being an 'official' php7 /
namespaced fork?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/j4mie/paris/issues/129#issuecomment-290661999>, or mute
the thread
