### ISSUE TITLE
Custom table name

### ISSUE THREAD

**Issue by Aldarien** [j4mie/paris#132]
When `$_table` and either `$_table_use_short_name` or `$short_table_names` are specified,  `$_table` is not used.

database.php:
`Model::$short_table_names = true;`

User.php:
```
class User extends Model
{
    public static $_table = 'users';
}
```

output:
`Error: table 'user' not found`

**Comment by tag** [comment]
Output looks correct.  

What are you expecting it to be?

**Comment by Aldarien** [comment]
Sorry
output is 'user'

**Comment by Aldarien** [comment]
Maybe it has to do with namespaces?

my class is namespaced in Models

`class User extends \Model`

**Comment by Aldarien** [comment]
Found my problem.

When calling the factory method for a namespaced model, the namespace has to be included.
eg.
`Model::factory('\Model\User')`
