### ISSUE TITLE
Transcation on delete query

### ISSUE THREAD

**Issue by navotera** [j4mie/paris#133]
Sorry i am opening an issue.... 
I want to create transaction query with this code :
```

    // Start a transaction
    ORM::get_db()->beginTransaction();

    //this work
    $prs = Model::factory('PenyediaJasaORM')->find_one(77);
    $prs->delete();

    //yes this not work, i know 
    $klas = Model::factory('PenyediaJasaKlasifikasiORM')->find_one(100);
    $klas->delete();


    // Commit a transaction
    ORM::get_db()->commit();
```

yes on $prs query it works. i made the $klas not work to see the outcome. but why i got error 'Fatal error: Call to a member function delete() on boolean in'.

i love on how parisorm create tidy and clean code ... but i think the appropriate error would be FALSE not FATAL ERROR since those query is transaction. 
i know that i could make code like this.. 

```
if($klas) 
$klas->delete();
```

but i think it would make me code many code and i think it would not be clean code to make....
please give suggestion to me if i am not fully understood transaction using multiple delete query.

thanks

**Comment by treffynnon** [comment]
I am really struggling to understand the issue here. Please could you describe what you're hoping to achieve? Are you hoping to rollback the transaction if there is a failure? In the case of errors please could you copy and paste the full message?

**Comment by navotera** [comment]
im closing issues (since  this question is not apporiate as issues) i asking this question in stackoverflow.. 
https://stackoverflow.com/questions/46535750/create-transaction-using-delete-method-failed/46535897?noredirect=1#comment80026483_46535897

hope anyone can contribute to answer my question.
