### ISSUE TITLE
how to do arithmetic operator in idiorm ? 

### ISSUE THREAD

**Issue by IceAisu** [j4mie/paris#134]
how to i write this in idiORM i already read the documentation but still dont understand,can u guys please help me,sorry for my bad english

i want to wrote this query in idiORM
SELECT cust_name,opening_amt, payment_amt, outstanding_amt
FROM customer
WHERE(outstanding_amt-payment_amt) as receiveAmt;

thanks in advance.

**Comment by treffynnon** [comment]
Please do not open an Idiorm issue against the Paris repository - duplicate issues across multiple repositories makes it difficult for project maintainers. I note that you've already opened an issue there where you've received some answers: https://github.com/j4mie/idiorm/issues/348
